### ISSUE TITLE
Scrobbling on start of video for recent Kodi Nightlies

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#33]
I could get a log but it is likely reproducible by getting a nightly build.

**Comment by kat953162** [comment]
This issue still perisists in the Alpha build and future builds. The addon doesn't appear to be looking at the length of the video, rather scrobbling at 0:00 or if only part of the video is loaded into memory it scrobbles when that hits the given percentage. @daviddavo

**Comment by daviddavo** [comment]
This looks important, so I look it asap

**Comment by daviddavo** [comment]
They have been working on an API that works with games, so they modified some methods. Changelog and wiki are still not available, but I will see what I can do

**Comment by kat953162** [comment]
@daviddavo any update on this? Perhaps something is mentioned for their Alpha releases (currently Alpha 3). Most plugin developers only cater to the Alpha releases as the nightlies are too difficult to follow through, and are only there for fixing Kodi-specific bugs.

**Comment by ekleop** [comment]
Tested on Kodi 17/18 Leia(Not Alpah\Beta), local + network source. And everything seem ok, 
Can you confirm?

**Comment by NoDruid** [comment]
Hey guys, hope this tool is still being developed.
I also have the issue that percentage value when the addon is supposed to scrobble is being ignored and it scrobbles on the start of the movie/tv episode.

I'm using the Kodi as part of OSMC OS on their Vero 4k+ hardware. Which is basically just debian with a few optimizations, I guess. (Link: https://osmc.tv/).

Anyway the problem started when I upgraded to Kodi Leia, I guess. Before that I remember it working just fine.

Hope you guys can fix that. Otherwise great job.

**Comment by ekleop** [comment]
1fc73aebe57b2f860ff38711c8fe8a32207824b7 fixed
